export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

//user Register
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//user Login
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

// subscribe teacher
export const SUBSCRIBE_TEACHER_BEGIN = "SUBSCRIBE_TEACHER_BEGIN";
export const SUBSCRIBE_TEACHER_SUCCESS = "SUBSCRIBE_TEACHER_SUCCESS";
export const SUBSCRIBE_TEACHER_END = "SUBSCRIBE_TEACHER_END";

//Get All users
export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

//Student - Get All Notices
export const STUDENT_GET_ALL_NOTICES_BEGIN = "STUDENT_GET_ALL_NOTICES_BEGIN";
export const STUDENT_GET_ALL_NOTICES_SUCCESS =
  "STUDENT_GET_ALL_NOTICES_SUCCESS";
export const STUDENT_GET_ALL_NOTICES_ERROR = "STUDENT_GET_ALL_NOTICES_ERROR";

//add Grade by admin
export const ADD_GRADE_BEGIN = "ADD_GRADE_BEGIN";
export const ADD_GRADE_SUCCESS = "ADD_GRADE_SUCCESS";
export const ADD_GRADE_ERROR = "ADD_GRADE_ERROR";

//Get All Grades by admin
export const GET_GRADES_BEGIN = "GET_GRADES_BEGIN";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_ERROR = "GET_GRADES_ERROR";

//Get All subjects by admin
export const GET_SUBJECTS_BEGIN = "GET_SUBJECTS_BEGIN";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_ERROR = "GET_SUBJECTS_ERROR";

//update Grade by admin
export const UPDATE_GRADE_BEGIN = "UPDATE_GRADE_BEGIN";
export const UPDATE_GRADE_SUCCESS = "UPDATE_GRADE_SUCCESS";
export const UPDATE_GRADE_ERROR = "UPDATE_GRADE_ERROR";

//delete grade by admin
export const DELETE_GRADE_BEGIN = "DELETE_GRADE_BEGIN";

//add Subject by admin
export const ADD_SUBJECT_BEGIN = "ADD_SUBJECT_BEGIN";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_ERROR = "ADD_SUBJECT_ERROR";

//update subject by admin
export const UPDATE_SUBJECT_BEGIN = "UPDATE_SUBJECT_BEGIN";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_ERROR = "GUPDATE_SUBJECT_ERROR";

//delete subject by admin
export const DELETE_SUBJECT_BEGIN = "DELETE_SUBJECT_BEGIN";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";

//password reset
export const LOGIN_NEWPASSWORD = "LOGIN_NEWPASSWORD";
export const LOGIN_NEWPASSWORD_COMPLETE = "LOGIN_NEWPASSWORD_COMPLETE";
export const LOGIN_NEWPASSWORD_ERROR = "LOGIN_NEWPASSWORD_ERROR";
